export type { TabsProps } from "./root/tabs"
export { Tabs } from "./root/tabs"
export type { TabsListProps } from "./list/tabs-list"
export { TabsList } from "./list/tabs-list"
export type { TabsTriggerProps } from "./trigger/tabs-trigger"
export { TabsTrigger } from "./trigger/tabs-trigger"
export type { TabsContentProps } from "./content/tabs-content"
export { TabsContent } from "./content/tabs-content"
export { tabsListVariants } from "./list/tabs-list"
