name: Docker build

on:
  pull_request:
  push:
    branches: [main]

permissions:
  contents: read

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: docker compose -f docker-compose.dev.yaml config --quiet
      - run: docker compose -f docker-compose.prod.yaml config --quiet
      - run: docker compose -f docker-compose.prod.yaml build
